[[ferrotherm]]
git-tree-sha1 = "89658c3f8847d251751e942727ba2e92a90436c3"
arch = "aarch64"
lazy = true
os = "macos"

    [[ferrotherm.download]]
    sha256 = "38f3598bac5dc06729ec2fc7584daee175107bd8d07bcd829cd45494617cbdf4"
    url = "https://github.com/dcharlot-physicalai-bmi/ferrotherm/releases/download/v0.17.0/ferrotherm.v0.17.0.aarch64-apple-darwin.tar.gz"
[[ferrotherm]]
git-tree-sha1 = "2111306a760ab83b1781043674fd441afbc233f3"
arch = "x86_64"
lazy = true
libc = "glibc"
os = "linux"

    [[ferrotherm.download]]
    sha256 = "5ec66be3f91c969bcd50b7890365a97eca2b528e3bf0d3a4387e6ab6d6641182"
    url = "https://github.com/dcharlot-physicalai-bmi/ferrotherm/releases/download/v0.17.0/ferrotherm.v0.17.0.x86_64-linux-gnu.tar.gz"
[[ferrotherm]]
git-tree-sha1 = "4009e737b1f3c93ee938cbf34c925838b2f3ad36"
arch = "x86_64"
lazy = true
os = "windows"

    [[ferrotherm.download]]
    sha256 = "9146ad7a667307112a4b771d288119d240d34e3542334a7ab46d3a905a1fbcb9"
    url = "https://github.com/dcharlot-physicalai-bmi/ferrotherm/releases/download/v0.17.0/ferrotherm.v0.17.0.x86_64-w64-mingw32.tar.gz"
