# GENERATED by scripts/gen-stubs.py -- do not edit.
#
# This package binds a C ABI through ctypes, so without this file an editor, a type checker
# and any model writing code against ferrotherm see a module of opaque callables: no
# parameter names, no types, no defaults. Guessing at a numeric API produces code that runs
# and is wrong, which is the failure a stub exists to prevent.
#
# It is generated rather than written because a hand-kept stub drifts one signature at a
# time, and every drift is a confident lie that still autocompletes. `check-stubs.sh`
# regenerates and diffs.

from typing import Any, Sequence

__version__: str

class Answer:
    """A solved problem, read by name."""
    def __init__(self, **kw: Any) -> None:
        ...
    @property
    def undecoded(self) -> 'list[str]':
        """The variables whose encoding was violated, which read as ``None``."""
        ...

class Bounds:
    """Lower bounds on the ground energy. All sound, so :attr:`best` is their maximum."""
    def __init__(self, decoupled: float, forest: float, odd_cycle: float, sdp: 'float | None') -> None:
        ...
    @property
    def best(self) -> float:
        """The tightest of them. Taking the maximum of sound bounds is sound."""
        ...
    @property
    def which(self) -> str:
        """Which bound set :attr:`best`. They disagree by a lot, and in both directions."""
        ...

class BranchResult:
    """What branch and bound found, and whether it proved it."""
    def __init__(self, energy: float, proved: bool, nodes: int) -> None:
        ...

class BreakoutRun:
    """A breakout-local-search run, with the evidence that it actually broke out."""
    def __init__(self, energy: float, descents: int, iterations_run: int, max_jump: int) -> None:
        ...

class Certificate:
    """What a run actually did, computed from its samples rather than from its own account."""
    def __init__(self, **kw: Any) -> None:
        ...
    @property
    def passed(self) -> bool:
        ...

class ClusterRun:
    """A PT+ICM run. ``moves`` is how many cluster moves actually fired — none means the replicas never disagreed, and the move was doing nothing."""
    def __init__(self, energy: float, moves: int) -> None:
        ...

class Estimate:
    """An expectation value with an error bar that accounts for how correlated the draws were."""
    def __init__(self, value: float, stderr: float, ess: float, tau_int: float) -> None:
        ...
    @property
    def ci95(self) -> 'tuple[float, float]':
        ...
    def covers(self, truth: float) -> bool:
        ...

class Grid:
    """A grid of variables, subscripted like an array."""
    def __init__(self, name: str, dims: 'tuple[int, ...]', vars: 'list[Variable]') -> None:
        ...
    @property
    def all(self) -> 'list[Variable]':
        """Every variable, row-major."""
        ...
    def column(self, *suffix: int) -> 'list[Variable]':
        """One column of the first dimension: ``a.column(s)`` is every worker for shift ``s``."""
        ...
    def row(self, *prefix: int) -> 'list[Variable]':
        """One row of the last dimension: ``a.row(w)`` is every shift for worker ``w``."""
        ...

class Hubo:
    """A higher-order model, solved without quadratising it."""
    def __init__(self, n: int) -> None:
        ...
    @property
    def accepted(self) -> int:
        ...
    def add(self, variables: Iterable[int], weight: float) -> 'Hubo':
        """Add one term of any arity. Returns self, so calls chain."""
        ...
    @property
    def ancillas_avoided(self) -> int:
        """An UPPER BOUND on what a pairwise reduction would have spent, not the cost."""
        ...
    def anneal(self, beta_min: float = 0.0, beta_max: float = 0.0, stages: int = 0, sweeps_per_stage: int = 0, seed: int = 1) -> float:
        """Anneal and return the best energy. Zero for any ladder parameter means its default."""
        ...
    def delta(self, i: int) -> float:
        """The energy change from flipping spin ``i``, in O(terms containing i)."""
        ...
    @property
    def energy(self) -> float:
        """Energy of the current state."""
        ...
    def joules_z1(self) -> float:
        """What the last run WOULD have cost on a Z1-class device (vendor SPICE, pre-silicon)."""
        ...
    @property
    def max_arity(self) -> int:
        ...
    @property
    def proposals(self) -> int:
        ...
    @property
    def state(self) -> List[int]:
        """The current state, copied out. Never a view into the library's memory."""
        ...
    @property
    def terms(self) -> int:
        ...

class Literal:
    """The claim that one variable takes one value. Multiply it by a number to weight it."""
    def __init__(self, var: 'Variable', value: int) -> None:
        ...

class Model:
    """A graph under construction: add couplings and biases, then :meth:`build` it."""
    def __init__(self, n: int) -> None:
        ...
    def bias(self, i: int, h: float) -> 'Model':
        """Add bias h_i. Returns self, so calls chain."""
        ...
    def build(self, beta: float = 1.0, seed: int = 0) -> 'Sim':
        """Consume this model into a simulation. The model is spent afterwards."""
        ...
    def couple(self, i: int, j: int, w: float) -> 'Model':
        """Add coupling J_ij. Returns self, so calls chain."""
        ...
    def couple_many(self, edges: Iterable[Sequence[float]]) -> 'Model':
        """Add many couplings from an iterable of ``(i, j, J)``."""
        ...

class PlanarCut:
    """An **exact** maximum cut on a planar graph. Not the best found — the maximum."""
    def __init__(self, cut: float, energy: float, faces: int, odd_faces: int) -> None:
        ...

class PopulationRun:
    """A population-annealing run, with the diagnostic that says whether to believe it."""
    def __init__(self, energy: float, ln_z: 'float | None', rho: float, population: int, ln_z_stderr: 'float | None' = None) -> None:
        ...
    def free_energy(self, beta: float, n: int) -> 'float | None':
        """``-ln Z / (beta * n)``, or ``None`` when ``ln_z`` is unavailable."""
        ...
    @property
    def trustworthy(self) -> bool:
        """``rho`` below a tenth of the population. A rule of thumb, not a theorem."""
        ...

class Problem:
    """A problem stated in its own terms, compiled to spins and sampled."""
    def __init__(self) -> None:
        ...
    def all_different(self, of: 'Sequence[Variable]', soft: 'float | None' = None) -> None:
        """Every one of these variables takes a different value."""
        ...
    @property
    def answers_kept(self) -> int:
        """How many answers the last solve kept — one per try."""
        ...
    def at_least(self, of: 'Sequence[Any]', k: int, value: int = 1, soft: 'float | None' = None) -> None:
        """At least ``k`` of them hold. Costs a slack variable."""
        ...
    def at_most(self, of: 'Sequence[Any]', k: int, value: int = 1, soft: 'float | None' = None) -> None:
        """At most ``k`` of them hold. Costs a slack variable."""
        ...
    def at_most_one(self, of: 'Sequence[Any]', soft: 'float | None' = None) -> None:
        """At most one of them holds."""
        ...
    def binary(self, name: str) -> Variable:
        """A variable that is 0 or 1."""
        ...
    def categorical(self, name: str, values: int, encoding: str = 'one-hot') -> Variable:
        """A variable holding one of ``values`` distinct values."""
        ...
    def certify(self, beta: float = 1.0, draws: int = 512, thin: int = 1) -> Certificate:
        """Ask whether the sampler that produced the answer was sampling what it claimed."""
        ...
    def equal(self, a: Variable, b: Variable, soft: 'float | None' = None) -> None:
        """``a`` and ``b`` must agree, or — with ``soft`` — had better."""
        ...
    def exactly(self, of: 'Sequence[Any]', k: int, value: int = 1, soft: 'float | None' = None) -> None:
        """Exactly ``k`` of them hold."""
        ...
    def exactly_one(self, of: 'Sequence[Any]', soft: 'float | None' = None) -> None:
        """Exactly one of them holds. Cheaper than ``exactly(of, 1)``: pairwise, with no slack."""
        ...
    def fix(self, v: Variable, value: int) -> None:
        """``v`` must take ``value``."""
        ...
    def ftp(self) -> str:
        """The compiled program in ``.ftp`` form, for running on another fabric."""
        ...
    def grid(self, name: str, dims: 'Sequence[int]', declare: Any = None) -> Grid:
        """A grid of variables, indexed and named for you."""
        ...
    def integer(self, name: str, lo: int, hi: int, encoding: str = 'one-hot') -> Variable:
        """A variable over the inclusive range ``lo``..``hi``."""
        ...
    def linear(self, terms: Any, rel: str, rhs: float, soft: 'float | None' = None) -> None:
        """A **weighted** linear row: ``3*a + 4*b + 5*c <= 7``."""
        ...
    def maximize(self, term: Any) -> None:
        """Prefer states where ``term`` is large."""
        ...
    def minimize(self, term: Any) -> None:
        """Prefer states where ``term`` is small."""
        ...
    def not_equal(self, a: Variable, b: Variable, soft: 'float | None' = None) -> None:
        """``a`` and ``b`` must differ, or — with ``soft`` — had better."""
        ...
    def ommx(self) -> 'tuple[bytes, float]':
        """The compiled model as an OMMX instance -- the interchange format this corner of the field converged on, so a ferrotherm program can be read by jijmodeling, Jij's stack, and anything else that speaks it. Returns the protobuf bytes and the offset the +/-1 to 0/1 substitution produced, ALREADY FOLDED INTO the instance -- ommx_objective(x) == ferrotherm_energy(s), so read the constant, do not add it."""
        ...
    def optima(self, tol: float = 1e-09) -> 'list[Answer]':
        """Every distinct way to do the job that the last :meth:`solve` found, best first."""
        ...
    def penalty(self, p: float) -> None:
        """Use exactly this penalty, disabling the automatic scaling."""
        ...
    def soften_last(self, weight: float) -> None:
        """Make the constraint added most recently a preference, priced at ``weight``."""
        ...
    def solve(self, tries: int = 12, beta_hot: float = 0.0, beta_cold: float = 0.0, stages: int = 0, sweeps: int = 0, method: str = 'anneal', effort: int = 0) -> Answer:
        """Compile and solve, keeping the best of ``tries`` anneals."""
        ...

class Rounded:
    """A state rounded out of the semidefinite relaxation, and whether the guarantee covers it."""
    def __init__(self, cut: float, energy: float, guaranteed: bool) -> None:
        ...

class SampleSet:
    """The states a run kept, and what may honestly be computed from them."""
    def __init__(self, sim: 'Sim') -> None:
        ...
    @property
    def best_energy(self) -> float:
        ...
    @property
    def chain_tau(self) -> float:
        """The slowest autocorrelation the chain showed. Every estimate is deflated by it."""
        ...
    def correlation(self, i: int, j: int) -> Estimate:
        """``<s_i s_j>``. This and :meth:`mean_spin` are the two moments contrastive divergence matches."""
        ...
    def degeneracy(self, tol: float = 1e-09) -> int:
        """Distinct states within ``tol`` of the lowest energy seen."""
        ...
    @property
    def distinct(self) -> int:
        """How many of the draws were DIFFERENT."""
        ...
    def magnetization(self) -> Estimate:
        """The order parameter, with its error bar."""
        ...
    def mean_energy(self) -> Estimate:
        """``<E>``, the internal energy."""
        ...
    def mean_spin(self, i: int) -> Estimate:
        """``<s_i>``, in ``[-1, 1]``."""
        ...
    def state(self, k: int) -> 'list[int]':
        ...

class Sim:
    """A running simulation. Use the constructors below rather than instantiating directly."""
    def __init__(self, handle: int) -> None:
        ...
    def anneal(self, beta_min: float = 0.05, beta_max: float = 4.0, stages: int = 60, sweeps_per_stage: int = 40) -> float:
        """Anneal down a geometric ladder, keeping the best state found. Returns its energy."""
        ...
    @property
    def beta(self) -> float:
        ...
    def bounds(self, forest_rounds: int = 40, max_cycle: int = 6, sdp_sweeps: int = 200, seed: int = 1) -> 'Bounds':
        """Every lower bound on the ground energy this library can compute, and the best of them."""
        ...
    def branch(self, max_nodes: int = 20000000) -> 'BranchResult':
        """Branch and bound from the current state, which it uses as its incumbent."""
        ...
    def breakout(self, iterations: int = 50000) -> 'BreakoutRun':
        """Breakout local search: steepest descent, with an adaptive perturbation between optima."""
        ...
    def certify(self, draws: int = 512, thin: int = 1) -> 'Certificate':
        """Sample and check the result."""
        ...
    def chain(self, v: int) -> 'list[int]':
        """The sites holding logical variable ``v``."""
        ...
    def clique_embed(self, hardware: 'Sim') -> int:
        """Store a **closed-form** structured clique embedding, where ``hardware`` has a known one."""
        ...
    def close(self) -> None:
        ...
    def cluster_anneal(self, rungs: int = 16, rounds: int = 400, beta_min: float = 0.1, beta_max: float = 6.0) -> 'ClusterRun':
        """Parallel tempering with isoenergetic cluster moves — the field's baseline."""
        ...
    def collect(self, draws: int = 512, thin: int = 1, burn_in: int = 0) -> 'SampleSet':
        """Draw states and keep them."""
        ...
    def copies(self, v: int) -> 'list[int]':
        """The nodes representing logical variable ``v``."""
        ...
    def embed(self, hardware: 'Sim', seed: int = 0, rounds: int = 0, budget: int = 0) -> bool:
        """Place this model onto ``hardware``, keeping the placement for the accessors below."""
        ...
    def embed_apply(self, hardware: 'Sim', chain_strength: float = 0.0) -> 'Sim':
        """Build the model that actually **runs** on the hardware, from a placement already found."""
        ...
    @property
    def embed_longest(self) -> int:
        """The longest chain — the number that decides whether an answer survives."""
        ...
    @property
    def embed_sites(self) -> int:
        """Physical sites the placement uses in total, or 0 if there is none."""
        ...
    @property
    def energy(self) -> float:
        ...
    def exact_ground_energy(self, max_width: int = 22) -> float | None:
        """Exact ground energy by variable elimination, or ``None`` if the graph is too dense."""
        ...
    def exact_ground_state(self, max_width: int = 22) -> 'list[int] | None':
        """The exact ground STATE, or ``None`` if the graph is too dense."""
        ...
    def exact_log_z(self, beta: float = 1.0, max_width: int = 22) -> float | None:
        """Exact log partition function, or ``None`` if too dense."""
        ...
    def exact_marginals(self, beta: float = 1.0, max_width: int = 22) -> 'list[float] | None':
        """Exact single-site ``P(s_i = +1)``, or ``None`` if the graph is too wide."""
        ...
    def exact_planar(self, scale: float = 1.0) -> 'PlanarCut':
        """**Exact** max-cut, in polynomial time, if this graph is planar."""
        ...
    def excess(self) -> float | None:
        """How far the current state sits above a planted instance's known optimum, as a fraction."""
        ...
    def fit(self, rows: Sequence[Sequence[int]], visible: int = 0, epochs: int = 0, k: int = 0, positive_sweeps: int = 0, learning_rate: float = 0.0, batch: int = 0, seed: int = 0) -> 'Sim':
        """Fit this model's weights to ``rows`` by contrastive divergence. Returns ``self``."""
        ...
    def gap(self, **kw: Any) -> float:
        """How far this simulation's current state is from optimal, at worst."""
        ...
    def goemans_williamson(self, hyperplanes: int = 64, seed: int = 1) -> 'Rounded':
        """Round the semidefinite relaxation to a state — the only guarantee in max-cut."""
        ...
    def hfs(self, steps: int = 400, block: int = 0) -> float:
        """Hamze-de Freitas-Selby: solve a low-treewidth **block** exactly, repeatedly."""
        ...
    def hfs_improving(self) -> int:
        """Block moves that strictly lowered the energy, or 0 if there was none."""
        ...
    def hfs_moves(self) -> int:
        """Block moves the last :meth:`hfs` ran, or 0 if there was none."""
        ...
    @property
    def joules(self) -> float:
        """Ledger priced at Z1-class device figures. This prices the modelled device, not your CPU."""
        ...
    @property
    def known_optimum(self) -> float | None:
        """The true ground energy, for a planted instance. ``None`` otherwise."""
        ...
    def ln_z_ais(self, beta: float, rungs: int = 64, sweeps: int = 2, runs: int = 128) -> float:
        """``ln Z(beta)`` by annealed importance sampling — the estimate whose *lower bound* is unconditional."""
        ...
    def ln_z_bar(self, beta: float, rungs: int = 32, burn_in: int = 200, draws: int = 2000) -> tuple:
        """``ln Z(beta)`` by Bennett acceptance-ratio steps from the exact anchor ``n ln 2``: ``(ln_z, stderr)``."""
        ...
    def ln_z_bethe(self, beta: float) -> float:
        """``ln Z(beta)`` by the Bethe free energy of loopy belief propagation: exact on a tree, an approximation with loops, ``nan`` if BP did not converge."""
        ...
    def ln_z_ess(self) -> float:
        """Effective sample size of the last :meth:`ln_z_ais` run's weights; near 1 means one walk dominated and the bound, while valid, is loose."""
        ...
    def ln_z_exact(self, beta: float) -> float:
        """Exact ``ln Z(beta)`` by variable elimination, or ``nan`` if the graph is too wide."""
        ...
    def ln_z_lower(self, delta: float = 0.01) -> float:
        """``ln Z >= ln_z_lower(delta)`` with probability at least ``1 - delta``, from the last :meth:`ln_z_ais`. ``nan`` with no run. See :meth:`ln_z_ess` for how loose it is."""
        ...
    def ln_z_mean_field(self, beta: float) -> float:
        """A **deterministic** lower bound on ``ln Z(beta)``: the Gibbs–Bogoliubov inequality at the naive mean-field fixed point. No sampling and no probability of failure — the bound holds at every magnetisation; the fixed point is only where it is tightest."""
        ...
    def ln_z_ti(self, beta: float, rungs: int = 32, burn_in: int = 200, draws: int = 2000, z: float = 3.0) -> tuple:
        """``ln Z(beta)`` by thermodynamic integration: ``(midpoint, lower, upper)``."""
        ...
    def log_likelihood(self, rows: Sequence[Sequence[int]], visible: int = 0) -> float:
        """Mean log-likelihood per row under this model, **exact**, by enumeration."""
        ...
    @property
    def logical_variables(self) -> int:
        """Logical variables this model stands for, or 0 if it was not produced by :meth:`sparsify`."""
        ...
    @property
    def magnetization(self) -> float:
        ...
    @property
    def node_updates(self) -> int:
        """Node updates charged to the ledger so far."""
        ...
    def numpy(self) -> Any:
        """The state as a NumPy array."""
        ...
    def population_anneal(self, population: int = 1000, sweeps: int = 4, beta_max: float = 6.0, stages: int = 100) -> 'PopulationRun':
        """Population annealing: ``population`` chains down one ladder, resampled at each rung."""
        ...
    def project(self) -> 'tuple[list[int], int]':
        """Read the current state back as a logical one, with the count of variables that BROKE."""
        ...
    def quantum_anneal(self, trotter: int = 4, beta: float = 10.0, gamma_max: float = 3.0, gamma_min: float = 0.05, steps: int = 200) -> float:
        """Simulated quantum annealing: path-integral Monte Carlo, not a quantum computer."""
        ...
    def qubit(self, i: int) -> 'int | None':
        """The **vendor's** linear qubit index for node ``i``, or ``None`` if this graph has none."""
        ...
    def site_lower_bound(self, hardware: 'Sim') -> int:
        """The fewest sites **any** embedding of this model onto ``hardware`` could use."""
        ...
    def sparsify(self, budget: int) -> 'Sim':
        """Rewrite this model so no variable has more than ``budget`` neighbours."""
        ...
    @property
    def sparsify_offset(self) -> float:
        """``E_logical = E_sparse + offset`` when every copy set agrees."""
        ...
    @property
    def spins(self) -> list[int]:
        """The state as a list of -1/+1."""
        ...
    def sweep(self, n: int = 1, threads: int = 1) -> int:
        """Run `n` chromatic block-Gibbs sweeps. Returns total sweeps so far."""
        ...
    def tabu(self, iterations: int = 50000, tenure: int = 0, restart_after: int = 5000) -> float:
        """Tabu search. Returns the best energy found and leaves that state behind."""
        ...
    def tabu_iterations(self) -> int:
        """Iterations the last :meth:`tabu` actually ran, or 0 if there was none."""
        ...
    @property
    def threads_used(self) -> int:
        """How many threads the last parallel sweep actually used, or 0 before one."""
        ...
    def toroidal_bound(self, scale: float = 1.0) -> 'ToroidalBound':
        """An **upper bound** on the maximum cut of a toroidal grid."""
        ...
    @property
    def treewidth(self) -> int:
        """Induced width of the elimination order. Exact inference costs ``2 ** treewidth``."""
        ...
    def unembed(self, variables: int) -> 'tuple[list[int], int]':
        """Read this embedded state back as a logical one, with the count of chains that **broke**."""
        ...

class Term:
    """A piece of an objective. Build these with arithmetic, not by calling the constructor."""
    def __init__(self, parts: 'list[tuple[float, list]]') -> None:
        ...
    @property
    def degree(self) -> int:
        """The widest product in this term. Three or more needs a higher-order reduction."""
        ...

class ToroidalBound:
    """An upper bound on the maximum cut of a torus, and whether it is achieved."""
    def __init__(self, cut: float, attained: bool) -> None:
        ...

class Variable:
    """A declared variable. Ask it for a literal with ``is_(value)``."""
    def __init__(self, problem: 'Problem', index: int, name: str, domain: str) -> None:
        ...
    def is_(self, value: int) -> Literal:
        """The literal "this variable takes ``value``"."""
        ...

class Violation:
    """A constraint the answer breaks, and by how much."""
    def __init__(self, detail: str, by: float, hard: bool = True) -> None:
        ...

def bars_and_stripes(side: int) -> list:
    """The ``side x side`` bars-and-stripes dataset, the standard tiny benchmark for fitting an EBM."""
    ...

def dbm(visible: int, layers: Sequence[int], beta: float = 1.0, seed: int = 0) -> Sim:
    """A deep Boltzmann machine's structure: ``visible`` spins, then each layer, chained."""
    ...

def from_spec(spec: dict, beta: float | None = None, seed: int | None = None) -> Sim:
    """Build from the same JSON shape the HTTP API and the MCP tools accept."""
    ...

def frustrated(l: int, loops: int, seed: int = 0, beta: float = 1.0) -> Sim:
    """A planted instance on an ``l`` by ``l`` lattice whose optimum is known by construction."""
    ...

def hardware_threads() -> int:
    """How many threads this machine can run at once, or 1 when that cannot be known."""
    ...

def lattice2d(l: int, j: float = 1.0, beta: float = 0.44, seed: int = 0) -> Sim:
    """2D nearest-neighbour Ising lattice, periodic, side `l`."""
    ...

def library_path() -> str:
    """Path of the shared library actually loaded. Useful when a wrong one is on the path."""
    ...

def onsager(beta: float) -> float:
    """Onsager's exact spontaneous magnetisation for the 2D Ising model. Ground truth."""
    ...

def pegasus(m: int = 16, j: float = 1.0, beta: float = 1.0, seed: int = 0) -> Sim:
    """The **Pegasus** graph ``P_m`` — the topology of every D-Wave *Advantage* processor."""
    ...

def rbm(visible: int, hidden: int, beta: float = 1.0, seed: int = 0) -> Sim:
    """A restricted Boltzmann machine's **structure**: complete bipartite, every weight zero."""
    ...

def ring(n: int, j: float = 1.0, h: float = 0.0, beta: float = 1.0, seed: int = 0) -> Sim:
    """A periodic chain of `n` nodes."""
    ...

def wishart(n: int, alpha: float = 0.5, seed: int = 0, beta: float = 1.0) -> Sim:
    """The Wishart planted ensemble: dense, with a known optimum, and hard below ``alpha`` of 1."""
    ...

def z1_grid(w: int, h: int, j: float = 1.0, hb: float = 0.0, beta: float = 1.0, seed: int = 0) -> Sim:
    """Z1-topology grid, degree 16, open boundaries."""
    ...

def zephyr(m: int = 15, t: int = 4, j: float = 1.0, beta: float = 1.0, seed: int = 0) -> Sim:
    """The **Zephyr** graph ``Z_{m,t}`` — the topology of D-Wave's *Advantage2* processors."""
    ...

__version__: Any
