//! Emit a board build for a real FPGA -- the **Alchitry Pt V2** (`XC7A100T-2FGG484I`) or the
//! **Kria KV260** (`XCK26-SFVC784-2LV`): a p-trit fabric and a p-bit fabric, each wrapped in a
//! top module that board can actually run, with the constraints and the Vivado scripts that say
//! what each unit costs in real silicon.
//!
//! ```text
//!   cargo run --release --example board_build -- <alchitry-pt|kv260|kv260-axi> <outdir> [pdit-sites] [pbit-side] [rom-bits]
//! ```
//!
//! # What this is for
//!
//! `examples/pdit_synth.rs` prices the two fabrics in yosys's generic cells, which is a ratio and
//! not a part: 4,027 cells per p-trit against 173 per p-bit, most of the p-trit's being three
//! Gumbel ROMs that are addressed by noise and so cannot constant-fold. A generic cell is not a
//! LUT6, and an FPGA's block RAM changes the answer again. This emits the same two fabrics for a
//! real device so Vivado can say what they cost there, and writes a bitstream that runs.
//!
//! # The two traps this is shaped around, both paid for once already
//!
//! **A fabric with no observable sink is deleted.** Synthesis keeps what reaches a port. The
//! p-bit fabric's own state is read by nothing, so an unwrapped instance optimises away to
//! almost nothing and a board then measures a correct zero for a design that is not there. Every
//! state bit is folded into one registered bit here, that bit drives a counter, and the counter
//! drives the LEDs -- and both the fabric instance and the fold carry `DONT_TOUCH`.
//!
//! **A frozen fabric measures nothing.** The couplings are written at a temperature where the
//! spins keep moving, so the LEDs report a fabric that is sampling rather than one that has
//! settled; `beta` is a parameter here for that reason.
//!
//! # The two boards
//!
//! **Alchitry Pt V2.** Board-level pins from the Alchitry Labs V2 source
//! (`hardware/pinout/PtV2TopPin.kt`, read 2026-09-15), all bank 14 at `LVCMOS33`: clock `W19`
//! (100 MHz), reset `N15` (active low), LEDs `P19 P20 T21 R19 V22 U21 T20 W20`. The first-batch
//! boards carry a pinout erratum on the TOP expansion connector; it does not touch these, which
//! are board-level. Artix-7 is not in every Vivado install -- check `get_parts xc7a*` before
//! building.
//!
//! **Kria KV260.** No programmable-logic I/O at all: the processing system supplies `pl_clk0` at
//! 100 MHz and the fabric toggles internally, which is the arrangement the 10.85 pJ per flip in
//! [`crate::ledger::KV260_MEASURED`] was metered through. `build.tcl` builds the block design
//! that provides that clock; the board's own INA260 on the 5 V rail is the instrument.
//!
//! **Kria KV260 with a read path (`kv260-axi`).** The build above has NO way to read a spin: its
//! block design disables every PS-to-PL AXI master, which is why that measurement could price a
//! flip and had to leave `e_read` unstated. This variant hangs [`FixedFabric::emit_axi_shell`] off
//! `M_AXI_HPM0_FPD` at `0xA000_0000`, and emits the host program and the protocol that meter a
//! read. Two things it is shaped around. The port's DATA WIDTH is a PS register (`afi_fs`,
//! `0xFD61_5000`) that the boot firmware sets and a bare `fpga_manager` load does not touch: on
//! the board this was written against it read `0xA00`, 128 bits, so the design says 128 and the
//! protocol reads the register back and refuses on a mismatch. And a read of a PL address NO
//! SLAVE ANSWERS can take the board down, so the host program is never pointed at the fabric until
//! `dmesg` shows this bitstream went in.

use ferrotherm::hdl::FixedFabric;
use ferrotherm::ising::lattice2d;
use ferrotherm::pdit::FixedPdit;
use ferrotherm::potts::{ring, Interaction};
use std::fs;
use std::path::Path;

/// Board-level pins of the Alchitry Pt V2, bank 14, `LVCMOS33`.
const CLOCK_PIN: &str = "W19";
const RESET_PIN: &str = "N15";
const LED_PINS: [&str; 8] = ["P19", "P20", "T21", "R19", "V22", "U21", "T20", "W20"];
/// The board's oscillator, nanoseconds.
const CLOCK_PERIOD_NS: f64 = 10.0;
/// `XC7A100T-2FGG484I` as Vivado names it.
const PT_PART: &str = "xc7a100tfgg484-2";
/// `XCK26-SFVC784-2LV` as Vivado names it, with the board part the block design needs.
const KV260_PART: &str = "xck26-sfvc784-2LV-c";
const KV260_BOARD: &str = "xilinx.com:kv260_som:part0:2.0";

/// A top module that runs `core` and cannot be optimised away: every state bit folds into one
/// registered bit, which clocks a counter, whose high bits drive the LEDs.
fn top(module: &str, core: &str, state_width: usize, phase_width: usize) -> String {
    format!(
        r#"// generated by ferrotherm::examples::alchitry_pt_build -- Alchitry Pt V2 top
module {module} (
    input  wire clk,
    input  wire rst_n,
    output reg  [7:0] led
);
  wire rst = ~rst_n;
  wire [{state_top}:0] state;
  wire [{phase_top}:0] phase;
  (* DONT_TOUCH = "true" *)
  {core} core (.clk(clk), .rst(rst), .en(1'b1), .state(state), .phase(phase));

  // The sink. Without something a port can reach, synthesis deletes the fabric and the board
  // measures a design that is not there.
  (* DONT_TOUCH = "true" *)
  reg fold = 1'b0;
  always @(posedge clk) fold <= ^state;

  // A fabric that is sampling toggles `fold`; one that has frozen does not, so the LEDs report
  // the difference rather than merely reporting power.
  reg [31:0] beat = 32'd0;
  always @(posedge clk) begin
    if (rst) beat <= 32'd0;
    else if (fold) beat <= beat + 32'd1;
  end
  always @(posedge clk) led <= beat[31:24];
endmodule
"#,
        state_top = state_width - 1,
        phase_top = phase_width - 1,
    )
}

/// The pin constraints and the clock period.
fn xdc() -> String {
    let mut s = String::from("# Alchitry Pt V2 -- board-level pins, bank 14, LVCMOS33\n");
    s.push_str(&format!(
        "set_property -dict {{PACKAGE_PIN {CLOCK_PIN} IOSTANDARD LVCMOS33}} [get_ports clk]\n\
         create_clock -period {CLOCK_PERIOD_NS:.3} -name sys_clk [get_ports clk]\n\
         set_property -dict {{PACKAGE_PIN {RESET_PIN} IOSTANDARD LVCMOS33}} [get_ports rst_n]\n"
    ));
    for (i, pin) in LED_PINS.iter().enumerate() {
        s.push_str(&format!(
            "set_property -dict {{PACKAGE_PIN {pin} IOSTANDARD LVCMOS33}} [get_ports {{led[{i}]}}]\n"
        ));
    }
    s.push_str(
        "\n# The configuration bank, so the bitstream loads rather than merely building.\n\
         set_property CFGBVS VCCO [current_design]\n\
         set_property CONFIG_VOLTAGE 3.3 [current_design]\n",
    );
    s
}

/// A Vivado script: synthesise, implement, report what it cost, and write the bitstream.
fn tcl(name: &str, core_file: &str) -> String {
    format!(
        r#"# generated by ferrotherm::examples::alchitry_pt_build
read_verilog {{{core_file} top_{name}.v}}
read_xdc pt_v2.xdc
synth_design -top top_{name} -part {PT_PART}
report_utilization -file {name}_utilization_synth.rpt
opt_design
place_design
phys_opt_design
route_design
report_utilization -file {name}_utilization.rpt
report_timing_summary -max_paths 5 -file {name}_timing.rpt
write_bitstream -force {name}.bit
puts "FERROTHERM_BUILD_DONE {name}"
"#
    )
}

/// The KV260 top: no programmable-logic I/O, the processing system's clock, and every state bit
/// folded into one registered bit -- the arrangement the board's 10.85 pJ per flip was metered
/// through. `DONT_TOUCH` on the instance and on the fold, because a fabric that no port can
/// reach is trimmed to about one lookup table and the board then measures a correct zero for a
/// design that is not there.
fn kv260_top(module: &str, core: &str, state_width: usize, phase_width: usize) -> String {
    format!(
        r#"// generated by ferrotherm::examples::board_build -- Kria KV260 power-measurement top
module {module}(input wire clk);
  reg [7:0] por = 8'hFF;
  always @(posedge clk) if (por != 8'd0) por <= por - 8'd1;
  wire rst = (por != 8'd0);
  (* DONT_TOUCH="true" *) wire [{state_top}:0] state;
  wire [{phase_top}:0] phase;
  (* DONT_TOUCH="true" *) {core} u_fabric (.clk(clk), .rst(rst), .en(1'b1), .state(state), .phase(phase));
  (* DONT_TOUCH="true" *) reg keep;
  always @(posedge clk) keep <= ^state;
endmodule

module design_{core}();
  wire pl_clk0;
  sys_wrapper ps_i (.pl_clk0(pl_clk0));
  {module}    u    (.clk(pl_clk0));
endmodule
"#,
        state_top = state_width - 1,
        phase_top = phase_width - 1,
    )
}

/// The KV260 build: the block design that supplies `pl_clk0`, then implementation to a bitstream.
fn kv260_tcl(name: &str, core_file: &str) -> String {
    format!(
        r#"# generated by ferrotherm::examples::board_build
set part  {KV260_PART}
set board {KV260_BOARD}
create_project ft_{name} ./ft_{name} -part $part -force
set_property board_part $board [current_project]

create_bd_design sys
create_bd_cell -type ip -vlnv [lindex [get_ipdefs *zynq_ultra_ps_e*] end] ps
apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e -config {{apply_board_preset 1}} [get_bd_cells ps]
set_property -dict [list   CONFIG.PSU__FPGA_PL0_ENABLE {{1}}   CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {{100}}   CONFIG.PSU__USE__M_AXI_GP0 {{0}} CONFIG.PSU__USE__M_AXI_GP1 {{0}} CONFIG.PSU__USE__M_AXI_GP2 {{0}} ] [get_bd_cells ps]
create_bd_port -dir O -type clk pl_clk0
connect_bd_net [get_bd_pins ps/pl_clk0] [get_bd_ports pl_clk0]
validate_bd_design
make_wrapper -files [get_files sys.bd] -top -import
generate_target all [get_files sys.bd]

add_files {{{core_file} kv260_top_{name}.v}}
set_property top design_{name} [current_fileset]
update_compile_order -fileset sources_1

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
puts "IMPL_STATUS: [get_property STATUS [get_runs impl_1]]  PROGRESS: [get_property PROGRESS [get_runs impl_1]]"
puts "BITSTREAM: [glob -nocomplain ./ft_{name}/ft_{name}.runs/impl_1/*.bit]"
puts "FERROTHERM_BUILD_DONE {name}"
"#
    )
}

/// The block-design face of the AXI shell: twelve address bits, so the segment is the 4 KB an
/// AXI4-Lite slave is allowed to be instead of the 4 GB a 32-bit port claims, and the clock tied
/// to the bus and the reset by attribute rather than by whatever inference decides.
fn kv260_axi_wrapper() -> String {
    String::from(
        r#"// generated by ferrotherm::examples::board_build -- block-design wrapper for the AXI shell
module ft_axi_bd (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi, ASSOCIATED_RESET rst_n" *)
    input  wire clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 rst_n RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire rst_n,
    input  wire [11:0] s_axi_awaddr,  input  wire [2:0] s_axi_awprot,
    input  wire        s_axi_awvalid, output wire s_axi_awready,
    input  wire [31:0] s_axi_wdata,   input  wire [3:0] s_axi_wstrb,
    input  wire        s_axi_wvalid,  output wire s_axi_wready,
    output wire [1:0]  s_axi_bresp,   output wire s_axi_bvalid,  input  wire s_axi_bready,
    input  wire [11:0] s_axi_araddr,  input  wire [2:0] s_axi_arprot,
    input  wire        s_axi_arvalid, output wire s_axi_arready,
    output wire [31:0] s_axi_rdata,   output wire [1:0] s_axi_rresp,
    output wire        s_axi_rvalid,  input  wire s_axi_rready
);
  ft_axi u (.clk(clk), .rst_n(rst_n),
    .s_axi_awaddr({20'd0, s_axi_awaddr}), .s_axi_awvalid(s_axi_awvalid), .s_axi_awready(s_axi_awready),
    .s_axi_wdata(s_axi_wdata), .s_axi_wstrb(s_axi_wstrb), .s_axi_wvalid(s_axi_wvalid), .s_axi_wready(s_axi_wready),
    .s_axi_bresp(s_axi_bresp), .s_axi_bvalid(s_axi_bvalid), .s_axi_bready(s_axi_bready),
    .s_axi_araddr({20'd0, s_axi_araddr}), .s_axi_arvalid(s_axi_arvalid), .s_axi_arready(s_axi_arready),
    .s_axi_rdata(s_axi_rdata), .s_axi_rresp(s_axi_rresp), .s_axi_rvalid(s_axi_rvalid), .s_axi_rready(s_axi_rready));
endmodule
"#,
    )
}

/// The KV260 build WITH a read path: the PS's `M_AXI_HPM0_FPD`, a `SmartConnect`, and the shell at
/// `0xA000_0000`. `hpm0_width` must equal what the running PS has in `afi_fs`.
fn kv260_axi_tcl(hpm0_width: u32) -> String {
    format!(
        r#"# generated by ferrotherm::examples::board_build -- KV260 with an AXI4-Lite read path
set part  {KV260_PART}
set board {KV260_BOARD}
create_project ft_axi ./ft_axi -part $part -force
set_property board_part $board [current_project]
add_files {{pbit.v ft_axi.v ft_axi_bd.v}}
update_compile_order -fileset sources_1

create_bd_design sys
create_bd_cell -type ip -vlnv [lindex [get_ipdefs *zynq_ultra_ps_e*] end] ps
apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e -config {{apply_board_preset 1}} [get_bd_cells ps]
set_property -dict [list   CONFIG.PSU__FPGA_PL0_ENABLE {{1}}   CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {{100}}   CONFIG.PSU__USE__M_AXI_GP0 {{1}} CONFIG.PSU__MAXIGP0__DATA_WIDTH {{{hpm0_width}}}   CONFIG.PSU__USE__M_AXI_GP1 {{0}} CONFIG.PSU__USE__M_AXI_GP2 {{0}} ] [get_bd_cells ps]
create_bd_cell -type module -reference ft_axi_bd fab
create_bd_cell -type ip -vlnv [lindex [get_ipdefs *proc_sys_reset*] end] rst
create_bd_cell -type ip -vlnv [lindex [get_ipdefs *smartconnect*] end] sc
set_property -dict [list CONFIG.NUM_SI {{1}} CONFIG.NUM_MI {{1}}] [get_bd_cells sc]
connect_bd_net [get_bd_pins ps/pl_clk0] [get_bd_pins ps/maxihpm0_fpd_aclk] [get_bd_pins sc/aclk] [get_bd_pins fab/clk] [get_bd_pins rst/slowest_sync_clk]
connect_bd_net [get_bd_pins ps/pl_resetn0] [get_bd_pins rst/ext_reset_in]
connect_bd_net [get_bd_pins rst/peripheral_aresetn] [get_bd_pins sc/aresetn] [get_bd_pins fab/rst_n]
connect_bd_intf_net [get_bd_intf_pins ps/M_AXI_HPM0_FPD] [get_bd_intf_pins sc/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins sc/M00_AXI] [get_bd_intf_pins fab/s_axi]
assign_bd_address -offset 0xA0000000 -range 4K [get_bd_addr_segs fab/s_axi/*]
validate_bd_design
foreach seg [get_bd_addr_segs -of_objects [get_bd_addr_spaces ps/Data]] {{
  puts "ADDR_SEG: $seg  OFFSET [get_property OFFSET $seg]  RANGE [get_property RANGE $seg]"
}}
make_wrapper -files [get_files sys.bd] -top -import
generate_target all [get_files sys.bd]
set_property top sys_wrapper [current_fileset]
update_compile_order -fileset sources_1

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
puts "IMPL_STATUS: [get_property STATUS [get_runs impl_1]]  PROGRESS: [get_property PROGRESS [get_runs impl_1]]"
open_run impl_1
report_utilization -file ft_axi_utilization.rpt
report_timing_summary -max_paths 5 -file ft_axi_timing.rpt
puts "BITSTREAM: [glob -nocomplain ./ft_axi/ft_axi.runs/impl_1/*.bit]"
puts "FERROTHERM_BUILD_DONE axi"
"#
    )
}

/// The host side of a metered read: one process, three arms, the fabric free-running in all of
/// them so that it is in every baseline.
fn host_reader_c(n_words: usize) -> String {
    format!(
        r#"// generated by ferrotherm::examples::board_build -- the host side of a metered read
// usage: ft_read <idle|halt|cpu|axi> <seconds>
//   idle  the fabric runs; this process sleeps.
//   halt  the fabric is HELD (run = 0: spins and generators frozen, clock still toggling); this
//         process sleeps. idle minus halt is the fabric's datapath power on ONE placement, with no
//         reload between the arms. Its known answer is zero sweeps per second.
//   cpu   the fabric runs; one core spins the SAME loop over {n_words} words of its own memory.
//   axi   the fabric runs; one core reads the fabric's {n_words} state words over AXI4-Lite.
// Every arm starts the fabric and reads the sweep counter before and after, so every arm reports
// a clock rate with a known answer: 100 MHz and two clocks a sweep is 5.0e7 sweeps per second. A
// port whose data width disagrees with the PS returns words that fail that, loudly.
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>
#define BASE 0xA0000000UL
#define NW {n_words}
static double now(void) {{ struct timespec t; clock_gettime(CLOCK_MONOTONIC, &t); return t.tv_sec + 1e-9 * t.tv_nsec; }}
int main(int argc, char **argv) {{
  if (argc != 3) {{ fprintf(stderr, "usage: ft_read <idle|halt|cpu|axi> <seconds>\n"); return 2; }}
  double secs = atof(argv[2]);
  int fd = open("/dev/mem", O_RDWR | O_SYNC);
  if (fd < 0) {{ perror("/dev/mem"); return 1; }}
  volatile uint32_t *r = mmap(0, 4096, PROT_READ | PROT_WRITE, MAP_SHARED, fd, BASE);
  if (r == MAP_FAILED) {{ perror("mmap"); return 1; }}
  r[2] = 0;          // target 0: free-run
  r[0] = (argv[1][0] == 'h') ? 0 : 1;   // run, or hold
  static volatile uint32_t local[NW];
  for (int k = 0; k < NW; k++) local[k] = 0x9E3779B9u * (k + 1);
  uint64_t reads = 0, pop_sum = 0; uint32_t pop_min = ~0u, pop_max = 0, acc = 0, changed = 0, prev0 = r[8];
  // The sweep counter is 32 bits at 5e7 a second: it wraps every 86 s, so it is differenced in
  // windows far shorter than that rather than once across the arm.
  uint32_t s_prev = r[3]; uint64_t sweeps = 0;
  double t0 = now(), t = t0, t_end = t0 + secs;
  while (t < t_end) {{
    if (argv[1][0] == 'a') {{
      for (int rep = 0; rep < 256; rep++) for (int k = 0; k < NW; k++) acc ^= r[8 + k];
      reads += 256ull * NW;
    }} else if (argv[1][0] == 'c') {{
      for (int rep = 0; rep < 256; rep++) for (int k = 0; k < NW; k++) acc ^= local[k];
      reads += 256ull * NW;
    }} else {{
      usleep(200000);
    }}
    uint32_t s_now = r[3]; sweeps += (uint32_t)(s_now - s_prev); s_prev = s_now;
    uint32_t p = r[4]; pop_sum += p; if (p < pop_min) pop_min = p; if (p > pop_max) pop_max = p;
    uint32_t w0 = r[8]; if (w0 != prev0) changed++; prev0 = w0;
    t = now();
  }}
  double dt = t - t0;
  printf("arm=%s seconds=%.6f word_reads=%llu reads_per_s=%.1f sweeps=%llu sweeps_per_s=%.1f pop_min=%u pop_max=%u word0_changes=%u acc=%08x\n",
         argv[1], dt, (unsigned long long)reads, reads / dt, (unsigned long long)sweeps, sweeps / dt, pop_min, pop_max, changed, acc);
  return 0;
}}
"#
    )
}

/// The protocol: interleaved arms in a random order per pass, the sensor sampled by the same code
/// in every arm, and three ways to refuse.
fn meter_protocol_py(bitstream: &str, hpm0_width: u32) -> String {
    let afi = match hpm0_width { 32 => 0, 64 => 1, _ => 2 };
    format!(
        r##"#!/usr/bin/env python3
# generated by ferrotherm::examples::board_build -- meter a READ on a KV260
# usage: sudo python3 meter_read.py [passes] [settle_s] [sample_s] [arms, default idle,cpu,axi]
# Writes one row per sensor sample and one row per arm. Refuses, rather than measuring, when:
#   - the PS's HPM0 data width is not the {hpm0_width} bits this bitstream was built for;
#   - dmesg does not show THIS bitstream going in (a failed load leaves the old design running
#     with state=operating, and a read of an address no slave answers can take the board down);
#   - another session's measurement is running on this shared board.
# And flags, rather than hides, any pass during which someone else loaded the FPGA.
import os, random, subprocess, sys, time
BIT = "{bitstream}"
HW = "/sys/class/hwmon/hwmon2/power1_input"
passes = int(sys.argv[1]) if len(sys.argv) > 1 else 8
settle = float(sys.argv[2]) if len(sys.argv) > 2 else 15.0
sample = float(sys.argv[3]) if len(sys.argv) > 3 else 25.0
ARMS = (sys.argv[4] if len(sys.argv) > 4 else "idle,cpu,axi").split(",")
def sh(c): return subprocess.run(c, shell=True, capture_output=True, text=True).stdout
def loads(): return int(sh("dmesg | grep -c 'writing.*FPGA'").strip() or 0)
def foreign(): return sh("pgrep -af 'kv_|flashv|flash8|flashfull' | grep -v pgrep").strip()
if foreign():
    sys.exit("REFUSED: another session is measuring on this board:\n" + foreign())
afi = int(sh("busybox devmem 0xFD615000 32").strip(), 16)
if (afi >> 8) & 3 != {afi}:
    sys.exit("REFUSED: afi_fs=%#x, HPM0 is not {hpm0_width} bits wide; this bitstream would read garbage" % afi)
before = int(sh("dmesg | grep -c 'writing %s'" % BIT).strip() or 0)
open("/sys/class/fpga_manager/fpga0/firmware", "w").write(BIT)
time.sleep(5)
after = int(sh("dmesg | grep -c 'writing %s'" % BIT).strip() or 0)
if after <= before:
    sys.exit("REFUSED: LOAD-NOOP, dmesg shows no write of " + BIT)
print("# meter_read bitstream=%s passes=%d settle=%.0f sample=%.0f afi_fs=%#x" % (BIT, passes, settle, sample, afi), flush=True)
for p in range(1, passes + 1):
    order = list(ARMS); random.shuffle(order)
    for arm in order:
        if foreign():
            print("# ABORTED pass=%d: another session started measuring" % p, flush=True); sys.exit(3)
        l0 = loads()
        proc = subprocess.Popen(["taskset", "-c", "3", "./ft_read", arm, str(settle + sample)], stdout=subprocess.PIPE, text=True)
        time.sleep(settle)
        t_end = time.time() + sample - 1.0
        while time.time() < t_end:
            print("S %d %s %s" % (p, arm, open(HW).read().strip()), flush=True)
            time.sleep(0.25)
        out = proc.communicate()[0].strip()
        print("A %d %s" % (p, out), flush=True)
        if loads() != l0:
            print("# FOREIGN-LOAD pass=%d arm=%s" % (p, arm), flush=True)
print("# done", flush=True)
"##
    )
}

/// Out-of-context synthesis of both fabrics: utilization without a board, which is the fastest
/// honest answer to what a unit costs on a part.
fn ooc_tcl(part: &str) -> String {
    format!(
        r#"# generated by ferrotherm::examples::board_build -- utilization only, no board needed
set part {part}
foreach {{src top}} {{pdit.v pdit pbit.v pbit}} {{
  puts "=== SYNTH $top ($src) ==="
  read_verilog $src
  synth_design -top $top -part $part -mode out_of_context
  puts "--- UTIL $top ---"
  report_utilization
  puts "=== DONE $top ==="
  close_design
}}
exit
"#
    )
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let board = args.get(1).map_or("alchitry-pt", String::as_str);
    let out = args.get(2).map_or("build/board", String::as_str);
    let pdit_sites: usize = args.get(3).map_or(16, |v| v.parse().expect("a site count"));
    let pbit_side: usize = args.get(4).map_or(8, |v| v.parse().expect("a lattice side"));
    let rom_bits: u32 = args.get(5).map_or(10, |v| v.parse().expect("ROM bits"));
    let part = match board {
        "alchitry-pt" => PT_PART,
        "kv260" | "kv260-axi" => KV260_PART,
        other => {
            eprintln!("unknown board {other}: expected alchitry-pt, kv260 or kv260-axi");
            std::process::exit(2);
        }
    };
    let dir = Path::new(out);
    fs::create_dir_all(dir).expect("output directory");

    // A three-state Potts ring, hot enough that the fabric keeps moving: a frozen fabric draws
    // the power of a fabric that is not sampling, and measures nothing.
    let potts = ring(pdit_sites, 3, 1.0, Interaction::Potts);
    let trit = FixedPdit::new(&potts, 0.6, 1, rom_bits).expect("a Potts ring");
    let sb = trit.state_bits();
    let pb = trit.phase_bits();
    fs::write(dir.join("pdit.v"), trit.emit_verilog("pdit")).expect("write");

    // A p-bit lattice, the fabric this crate metered on a KV260 at 10.85 pJ per flip.
    let g = lattice2d(pbit_side, 1.0);
    let bit = FixedFabric::new(&g, 0.6, 1);
    fs::write(dir.join("pbit.v"), bit.emit_verilog("pbit")).expect("write");

    // Utilization needs no board, and is the fastest honest answer to what a unit costs.
    fs::write(dir.join("ooc.tcl"), ooc_tcl(part)).expect("write");

    match board {
        "alchitry-pt" => {
            fs::write(dir.join("top_pdit.v"), top("top_pdit", "pdit", trit.n * sb, pb)).expect("write");
            fs::write(dir.join("top_pbit.v"), top("top_pbit", "pbit", g.n, 1)).expect("write");
            fs::write(dir.join("pdit.tcl"), tcl("pdit", "pdit.v")).expect("write");
            fs::write(dir.join("pbit.tcl"), tcl("pbit", "pbit.v")).expect("write");
            fs::write(dir.join("pt_v2.xdc"), xdc()).expect("write");
        }
        "kv260-axi" => {
            // What the running PS had in `afi_fs` on the board this was written against. The
            // protocol reads the register back and refuses if the board disagrees.
            let hpm0_width = 128;
            fs::write(dir.join("ft_axi.v"), bit.emit_axi_shell("ft_axi", "pbit", "clk")).expect("write");
            fs::write(dir.join("ft_axi_bd.v"), kv260_axi_wrapper()).expect("write");
            fs::write(dir.join("axi.tcl"), kv260_axi_tcl(hpm0_width)).expect("write");
            fs::write(dir.join("ft_read.c"), host_reader_c(g.n.div_ceil(32))).expect("write");
            fs::write(dir.join("meter_read.py"), meter_protocol_py("ft_axi.bit.bin", hpm0_width)).expect("write");
            fs::write(dir.join("ft_axi.bif"), "all:\n{\n  [destination_device = pl] ft_axi.bit\n}\n").expect("write");
        }
        _ => {
            fs::write(dir.join("kv260_top_pdit.v"), kv260_top("kv260_top_pdit", "pdit", trit.n * sb, pb)).expect("write");
            fs::write(dir.join("kv260_top_pbit.v"), kv260_top("kv260_top_pbit", "pbit", g.n, 1)).expect("write");
            fs::write(dir.join("pdit.tcl"), kv260_tcl("pdit", "pdit.v")).expect("write");
            fs::write(dir.join("pbit.tcl"), kv260_tcl("pbit", "pbit.v")).expect("write");
        }
    }

    println!("{board} ({part}) build written to {out}");
    println!(
        "  p-trit fabric: {} sites of radix {}, {} state bits each, {} colour classes, {rom_bits}-bit Gumbel ROM",
        trit.n,
        trit.q,
        sb,
        trit.classes.len()
    );
    println!(
        "  p-bit fabric:  {} spins on a {pbit_side}x{pbit_side} lattice, {} colour classes",
        g.n,
        g.classes.len()
    );
    println!();
    println!("ooc.tcl reports what each unit costs on this part; the per-board scripts implement");
    println!("and write a bitstream. Divide the utilization by the unit count, and read the");
    println!("timing summary for the clock the part will hold.");
}
