//! Emit a board build for a real FPGA -- the **Alchitry Pt V2** (`XC7A100T-2FGG484I`) or the
//! **Kria KV260** (`XCK26-SFVC784-2LV`): a p-trit fabric and a p-bit fabric, each wrapped in a
//! top module that board can actually run, with the constraints and the Vivado scripts that say
//! what each unit costs in real silicon.
//!
//! ```text
//!   cargo run --release --example board_build -- <alchitry-pt|kv260> <outdir> [pdit-sites] [pbit-side] [rom-bits]
//! ```
//!
//! # What this is for
//!
//! `examples/pdit_synth.rs` prices the two fabrics in yosys's generic cells, which is a ratio and
//! not a part: 4,027 cells per p-trit against 173 per p-bit, most of the p-trit's being three
//! Gumbel ROMs that are addressed by noise and so cannot constant-fold. A generic cell is not a
//! LUT6, and an FPGA's block RAM changes the answer again. This emits the same two fabrics for a
//! real device so Vivado can say what they cost there, and writes a bitstream that runs.
//!
//! # The two traps this is shaped around, both paid for once already
//!
//! **A fabric with no observable sink is deleted.** Synthesis keeps what reaches a port. The
//! p-bit fabric's own state is read by nothing, so an unwrapped instance optimises away to
//! almost nothing and a board then measures a correct zero for a design that is not there. Every
//! state bit is folded into one registered bit here, that bit drives a counter, and the counter
//! drives the LEDs -- and both the fabric instance and the fold carry `DONT_TOUCH`.
//!
//! **A frozen fabric measures nothing.** The couplings are written at a temperature where the
//! spins keep moving, so the LEDs report a fabric that is sampling rather than one that has
//! settled; `beta` is a parameter here for that reason.
//!
//! # The two boards
//!
//! **Alchitry Pt V2.** Board-level pins from the Alchitry Labs V2 source
//! (`hardware/pinout/PtV2TopPin.kt`, read 2026-09-15), all bank 14 at `LVCMOS33`: clock `W19`
//! (100 MHz), reset `N15` (active low), LEDs `P19 P20 T21 R19 V22 U21 T20 W20`. The first-batch
//! boards carry a pinout erratum on the TOP expansion connector; it does not touch these, which
//! are board-level. Artix-7 is not in every Vivado install -- check `get_parts xc7a*` before
//! building.
//!
//! **Kria KV260.** No programmable-logic I/O at all: the processing system supplies `pl_clk0` at
//! 100 MHz and the fabric toggles internally, which is the arrangement the 10.85 pJ per flip in
//! [`crate::ledger::KV260_MEASURED`] was metered through. `build.tcl` builds the block design
//! that provides that clock; the board's own INA260 on the 5 V rail is the instrument.

use ferrotherm::hdl::FixedFabric;
use ferrotherm::ising::lattice2d;
use ferrotherm::pdit::FixedPdit;
use ferrotherm::potts::{ring, Interaction};
use std::fs;
use std::path::Path;

/// Board-level pins of the Alchitry Pt V2, bank 14, `LVCMOS33`.
const CLOCK_PIN: &str = "W19";
const RESET_PIN: &str = "N15";
const LED_PINS: [&str; 8] = ["P19", "P20", "T21", "R19", "V22", "U21", "T20", "W20"];
/// The board's oscillator, nanoseconds.
const CLOCK_PERIOD_NS: f64 = 10.0;
/// `XC7A100T-2FGG484I` as Vivado names it.
const PT_PART: &str = "xc7a100tfgg484-2";
/// `XCK26-SFVC784-2LV` as Vivado names it, with the board part the block design needs.
const KV260_PART: &str = "xck26-sfvc784-2LV-c";
const KV260_BOARD: &str = "xilinx.com:kv260_som:part0:2.0";

/// A top module that runs `core` and cannot be optimised away: every state bit folds into one
/// registered bit, which clocks a counter, whose high bits drive the LEDs.
fn top(module: &str, core: &str, state_width: usize, phase_width: usize) -> String {
    format!(
        r#"// generated by ferrotherm::examples::alchitry_pt_build -- Alchitry Pt V2 top
module {module} (
    input  wire clk,
    input  wire rst_n,
    output reg  [7:0] led
);
  wire rst = ~rst_n;
  wire [{state_top}:0] state;
  wire [{phase_top}:0] phase;
  (* DONT_TOUCH = "true" *)
  {core} core (.clk(clk), .rst(rst), .en(1'b1), .state(state), .phase(phase));

  // The sink. Without something a port can reach, synthesis deletes the fabric and the board
  // measures a design that is not there.
  (* DONT_TOUCH = "true" *)
  reg fold = 1'b0;
  always @(posedge clk) fold <= ^state;

  // A fabric that is sampling toggles `fold`; one that has frozen does not, so the LEDs report
  // the difference rather than merely reporting power.
  reg [31:0] beat = 32'd0;
  always @(posedge clk) begin
    if (rst) beat <= 32'd0;
    else if (fold) beat <= beat + 32'd1;
  end
  always @(posedge clk) led <= beat[31:24];
endmodule
"#,
        state_top = state_width - 1,
        phase_top = phase_width - 1,
    )
}

/// The pin constraints and the clock period.
fn xdc() -> String {
    let mut s = String::from("# Alchitry Pt V2 -- board-level pins, bank 14, LVCMOS33\n");
    s.push_str(&format!(
        "set_property -dict {{PACKAGE_PIN {CLOCK_PIN} IOSTANDARD LVCMOS33}} [get_ports clk]\n\
         create_clock -period {CLOCK_PERIOD_NS:.3} -name sys_clk [get_ports clk]\n\
         set_property -dict {{PACKAGE_PIN {RESET_PIN} IOSTANDARD LVCMOS33}} [get_ports rst_n]\n"
    ));
    for (i, pin) in LED_PINS.iter().enumerate() {
        s.push_str(&format!(
            "set_property -dict {{PACKAGE_PIN {pin} IOSTANDARD LVCMOS33}} [get_ports {{led[{i}]}}]\n"
        ));
    }
    s.push_str(
        "\n# The configuration bank, so the bitstream loads rather than merely building.\n\
         set_property CFGBVS VCCO [current_design]\n\
         set_property CONFIG_VOLTAGE 3.3 [current_design]\n",
    );
    s
}

/// A Vivado script: synthesise, implement, report what it cost, and write the bitstream.
fn tcl(name: &str, core_file: &str) -> String {
    format!(
        r#"# generated by ferrotherm::examples::alchitry_pt_build
read_verilog {{{core_file} top_{name}.v}}
read_xdc pt_v2.xdc
synth_design -top top_{name} -part {PT_PART}
report_utilization -file {name}_utilization_synth.rpt
opt_design
place_design
phys_opt_design
route_design
report_utilization -file {name}_utilization.rpt
report_timing_summary -max_paths 5 -file {name}_timing.rpt
write_bitstream -force {name}.bit
puts "FERROTHERM_BUILD_DONE {name}"
"#
    )
}

/// The KV260 top: no programmable-logic I/O, the processing system's clock, and every state bit
/// folded into one registered bit -- the arrangement the board's 10.85 pJ per flip was metered
/// through. `DONT_TOUCH` on the instance and on the fold, because a fabric that no port can
/// reach is trimmed to about one lookup table and the board then measures a correct zero for a
/// design that is not there.
fn kv260_top(module: &str, core: &str, state_width: usize, phase_width: usize) -> String {
    format!(
        r#"// generated by ferrotherm::examples::board_build -- Kria KV260 power-measurement top
module {module}(input wire clk);
  reg [7:0] por = 8'hFF;
  always @(posedge clk) if (por != 8'd0) por <= por - 8'd1;
  wire rst = (por != 8'd0);
  (* DONT_TOUCH="true" *) wire [{state_top}:0] state;
  wire [{phase_top}:0] phase;
  (* DONT_TOUCH="true" *) {core} u_fabric (.clk(clk), .rst(rst), .en(1'b1), .state(state), .phase(phase));
  (* DONT_TOUCH="true" *) reg keep;
  always @(posedge clk) keep <= ^state;
endmodule

module design_{core}();
  wire pl_clk0;
  sys_wrapper ps_i (.pl_clk0(pl_clk0));
  {module}    u    (.clk(pl_clk0));
endmodule
"#,
        state_top = state_width - 1,
        phase_top = phase_width - 1,
    )
}

/// The KV260 build: the block design that supplies `pl_clk0`, then implementation to a bitstream.
fn kv260_tcl(name: &str, core_file: &str) -> String {
    format!(
        r#"# generated by ferrotherm::examples::board_build
set part  {KV260_PART}
set board {KV260_BOARD}
create_project ft_{name} ./ft_{name} -part $part -force
set_property board_part $board [current_project]

create_bd_design sys
create_bd_cell -type ip -vlnv [lindex [get_ipdefs *zynq_ultra_ps_e*] end] ps
apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e -config {{apply_board_preset 1}} [get_bd_cells ps]
set_property -dict [list   CONFIG.PSU__FPGA_PL0_ENABLE {{1}}   CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {{100}}   CONFIG.PSU__USE__M_AXI_GP0 {{0}} CONFIG.PSU__USE__M_AXI_GP1 {{0}} CONFIG.PSU__USE__M_AXI_GP2 {{0}} ] [get_bd_cells ps]
create_bd_port -dir O -type clk pl_clk0
connect_bd_net [get_bd_pins ps/pl_clk0] [get_bd_ports pl_clk0]
validate_bd_design
make_wrapper -files [get_files sys.bd] -top -import
generate_target all [get_files sys.bd]

add_files {{{core_file} kv260_top_{name}.v}}
set_property top design_{name} [current_fileset]
update_compile_order -fileset sources_1

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
puts "IMPL_STATUS: [get_property STATUS [get_runs impl_1]]  PROGRESS: [get_property PROGRESS [get_runs impl_1]]"
puts "BITSTREAM: [glob -nocomplain ./ft_{name}/ft_{name}.runs/impl_1/*.bit]"
puts "FERROTHERM_BUILD_DONE {name}"
"#
    )
}

/// Out-of-context synthesis of both fabrics: utilization without a board, which is the fastest
/// honest answer to what a unit costs on a part.
fn ooc_tcl(part: &str) -> String {
    format!(
        r#"# generated by ferrotherm::examples::board_build -- utilization only, no board needed
set part {part}
foreach {{src top}} {{pdit.v pdit pbit.v pbit}} {{
  puts "=== SYNTH $top ($src) ==="
  read_verilog $src
  synth_design -top $top -part $part -mode out_of_context
  puts "--- UTIL $top ---"
  report_utilization
  puts "=== DONE $top ==="
  close_design
}}
exit
"#
    )
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let board = args.get(1).map_or("alchitry-pt", String::as_str);
    let out = args.get(2).map_or("build/board", String::as_str);
    let pdit_sites: usize = args.get(3).map_or(16, |v| v.parse().expect("a site count"));
    let pbit_side: usize = args.get(4).map_or(8, |v| v.parse().expect("a lattice side"));
    let rom_bits: u32 = args.get(5).map_or(10, |v| v.parse().expect("ROM bits"));
    let part = match board {
        "alchitry-pt" => PT_PART,
        "kv260" => KV260_PART,
        other => {
            eprintln!("unknown board {other}: expected alchitry-pt or kv260");
            std::process::exit(2);
        }
    };
    let dir = Path::new(out);
    fs::create_dir_all(dir).expect("output directory");

    // A three-state Potts ring, hot enough that the fabric keeps moving: a frozen fabric draws
    // the power of a fabric that is not sampling, and measures nothing.
    let potts = ring(pdit_sites, 3, 1.0, Interaction::Potts);
    let trit = FixedPdit::new(&potts, 0.6, 1, rom_bits).expect("a Potts ring");
    let sb = trit.state_bits();
    let pb = trit.phase_bits();
    fs::write(dir.join("pdit.v"), trit.emit_verilog("pdit")).expect("write");

    // A p-bit lattice, the fabric this crate metered on a KV260 at 10.85 pJ per flip.
    let g = lattice2d(pbit_side, 1.0);
    let bit = FixedFabric::new(&g, 0.6, 1);
    fs::write(dir.join("pbit.v"), bit.emit_verilog("pbit")).expect("write");

    // Utilization needs no board, and is the fastest honest answer to what a unit costs.
    fs::write(dir.join("ooc.tcl"), ooc_tcl(part)).expect("write");

    match board {
        "alchitry-pt" => {
            fs::write(dir.join("top_pdit.v"), top("top_pdit", "pdit", trit.n * sb, pb)).expect("write");
            fs::write(dir.join("top_pbit.v"), top("top_pbit", "pbit", g.n, 1)).expect("write");
            fs::write(dir.join("pdit.tcl"), tcl("pdit", "pdit.v")).expect("write");
            fs::write(dir.join("pbit.tcl"), tcl("pbit", "pbit.v")).expect("write");
            fs::write(dir.join("pt_v2.xdc"), xdc()).expect("write");
        }
        _ => {
            fs::write(dir.join("kv260_top_pdit.v"), kv260_top("kv260_top_pdit", "pdit", trit.n * sb, pb)).expect("write");
            fs::write(dir.join("kv260_top_pbit.v"), kv260_top("kv260_top_pbit", "pbit", g.n, 1)).expect("write");
            fs::write(dir.join("pdit.tcl"), kv260_tcl("pdit", "pdit.v")).expect("write");
            fs::write(dir.join("pbit.tcl"), kv260_tcl("pbit", "pbit.v")).expect("write");
        }
    }

    println!("{board} ({part}) build written to {out}");
    println!(
        "  p-trit fabric: {} sites of radix {}, {} state bits each, {} colour classes, {rom_bits}-bit Gumbel ROM",
        trit.n,
        trit.q,
        sb,
        trit.classes.len()
    );
    println!(
        "  p-bit fabric:  {} spins on a {pbit_side}x{pbit_side} lattice, {} colour classes",
        g.n,
        g.classes.len()
    );
    println!();
    println!("ooc.tcl reports what each unit costs on this part; the per-board scripts implement");
    println!("and write a bitstream. Divide the utilization by the unit count, and read the");
    println!("timing summary for the clock the part will hold.");
}
